POST http://localhost:{PORT}/items
content-type: application/json

{
  "title": "item-01"
}

###

# GET http://localhost:{PORT}/items?search={search term}
GET http://localhost:{PORT}/items

###

PUT http://localhost:{PORT}/items
content-type: application/json

{
  "title": "item-01"
}

###

DELETE http://localhost:{PORT}/items/{ID}